#coding=utf-8
import struct
import binascii
import os


print "hehe"
id = 305419896
base_file_name = "test.txt"
base_file = open(base_file_name, "w+")
table_base = \
"/**\n \
* @file:   table_base.hpp\n \
* @author: SeanLiu <darkdawn@sina.com>\n \
* @brief:  The file is generated by tools. Don't modify it.\n \
*/\n \
#include <map>\n\n \
\n"

base_file.write(table_base)
base_file.close()

"""
parsedata_id = struct.pack("L",id)
data += parsedata_id
text = 'Staff 呵呵'
WriteFileData = open('pythonfile.dat','wb+')
data += struct.pack("L",len(text))
data += text
WriteFileData.write(data)
WriteFileData.close()
"""